export const glossaryTerms: { term: string; definition: string }[] = [
  { term: 'Al dente', definition: 'Italian for "to the tooth." Pasta cooked until firm to the bite, not soft.' },
  { term: 'Al forno', definition: 'Italian for "in the oven." Baked dishes such as pasta al forno.' },
  { term: 'Au gratin', definition: 'A dish topped with breadcrumbs, cheese, or butter and browned under a broiler or in the oven.' },
  { term: 'Bain-marie', definition: 'A water bath used to gently cook or keep food warm. A pan is placed in a larger pan of simmering water.' },
  { term: 'Bake', definition: 'To cook food in an oven using dry heat, typically at moderate temperatures (around 350°F).' },
  { term: 'Bard', definition: 'To wrap meat (often lean cuts) with fat, such as bacon or pork fat, to keep it moist during cooking.' },
  { term: 'Baste', definition: 'To moisten food with liquid (pan drippings, melted butter, or stock) while cooking to add flavor and prevent drying.' },
  { term: 'Béarnaise', definition: 'A classic French sauce made with egg yolks, butter, shallots, tarragon, and vinegar. Served with steak.' },
  { term: 'Béchamel', definition: 'A white sauce made from milk thickened with a roux (butter and flour). One of the five French mother sauces.' },
  { term: 'Blanch', definition: 'To briefly boil food (often vegetables) then submerge in ice water to stop cooking. Preserves color and texture.' },
  { term: 'Blind bake', definition: 'To bake a pastry shell without filling, often weighted with pie weights to prevent puffing.' },
  { term: 'Braise', definition: 'To cook food slowly in a covered pot with a small amount of liquid. Ideal for tougher cuts of meat.' },
  { term: 'Bread', definition: 'To coat food (e.g., cutlets) with flour, beaten egg, then breadcrumbs before frying.' },
  { term: 'Brine', definition: 'A saltwater solution used to soak meat or poultry before cooking to add moisture and flavor.' },
  { term: 'Broil', definition: 'To cook using high, direct heat from above. Food is placed close to the heating element.' },
  { term: 'Bouquet garni', definition: 'A bundle of herbs (typically thyme, bay leaf, and parsley) tied together and used to flavor stocks and stews.' },
  { term: 'Brunoise', definition: 'A very fine dice (about 1/8 inch). Vegetables are first julienned, then cut crosswise.' },
  { term: 'Butterfly', definition: 'To cut food (e.g., shrimp or chicken breast) in half horizontally and spread open like a butterfly.' },
  { term: 'Caramelize', definition: 'To heat sugar until it melts and turns golden brown. Also refers to browning onions or other foods to develop sweetness.' },
  { term: 'Chiffonade', definition: 'To cut leafy herbs or greens into thin ribbons by stacking leaves, rolling tightly, and slicing crosswise.' },
  { term: 'Chop', definition: 'To cut food into irregular pieces. Size can vary from coarse to fine.' },
  { term: 'Clarify', definition: 'To remove impurities from butter or stock. Clarified butter has milk solids removed and has a higher smoke point.' },
  { term: 'Compote', definition: 'Fruit cooked in sugar syrup, often served as a dessert or accompaniment.' },
  { term: 'Confit', definition: 'A preservation method where food (traditionally duck) is cooked slowly in its own fat and stored in that fat.' },
  { term: 'Coulis', definition: 'A thick sauce made from puréed and strained fruit or vegetables. Often used as a garnish.' },
  { term: 'Cream', definition: 'In baking, to beat butter and sugar together until light and fluffy. Incorporates air for leavening.' },
  { term: 'Crème fraîche', definition: 'A cultured cream with a tangy flavor and thick consistency. Used in sauces and desserts.' },
  { term: 'Cure', definition: 'To preserve food using salt, sugar, nitrates, or smoke. Examples: cured bacon, gravlax.' },
  { term: 'Dash', definition: 'A small amount of an ingredient, roughly 1/8 teaspoon. Often used for spices or liquid seasonings.' },
  { term: 'Deglaze', definition: 'To add liquid (wine, stock) to a hot pan to loosen browned bits (fond) from the bottom, creating a flavorful sauce.' },
  { term: 'Dice', definition: 'To cut food into small, uniform cubes. Sizes range from fine (1/8 inch) to large (1/2 inch).' },
  { term: 'Double boiler', definition: 'Two nested pots: the bottom holds simmering water; the top holds food that needs gentle, indirect heat.' },
  { term: 'Dredge', definition: 'To coat food with flour or another dry ingredient before frying or cooking.' },
  { term: 'Drizzle', definition: 'To pour a thin stream of liquid (oil, sauce) over food in a light, even manner.' },
  { term: 'Dust', definition: 'To lightly sprinkle a surface or food with flour, sugar, or cocoa.' },
  { term: 'Emulsify', definition: 'To combine two liquids that normally do not mix (e.g., oil and vinegar) into a stable mixture, often using an emulsifier like egg yolk.' },
  { term: 'En papillote', definition: 'French for "in parchment." Food is wrapped in parchment paper and baked, steaming in its own juices.' },
  { term: 'Fillet', definition: 'To remove bones from meat or fish. Also refers to a boneless cut.' },
  { term: 'Flambé', definition: 'To ignite alcohol (e.g., brandy) added to a dish to burn off the alcohol and add flavor.' },
  { term: 'Fold', definition: 'To gently combine a lighter mixture (e.g., whipped cream) into a heavier one using a spatula in a cutting motion.' },
  { term: 'Fond', definition: 'The browned bits left in a pan after searing meat. Deglazing releases their flavor into sauces.' },
  { term: 'Fry', definition: 'To cook food in hot fat. Deep-frying submerges food; shallow or pan-frying uses less oil.' },
  { term: 'Garnish', definition: 'A decorative or flavorful finishing touch added to a dish before serving.' },
  { term: 'Glaze', definition: 'To coat food with a glossy liquid (sugar syrup, reduced stock) for shine and flavor.' },
  { term: 'Grate', definition: 'To reduce food to small pieces by rubbing it against a grater. Used for cheese, vegetables, citrus zest.' },
  { term: 'Grease', definition: 'To coat a pan or baking dish with fat (butter, oil) to prevent sticking.' },
  { term: 'Grill', definition: 'To cook food over direct heat, often on a grate. Can be done on a gas grill, charcoal grill, or grill pan.' },
  { term: 'Hollandaise', definition: 'A rich French sauce of egg yolks, butter, and lemon. One of the five mother sauces.' },
  { term: 'Infuse', definition: 'To steep herbs, spices, or other flavorings in a liquid to extract their flavor.' },
  { term: 'Julienne', definition: 'To cut food into long, thin strips, about 1/8 inch thick. Similar to matchsticks.' },
  { term: 'Knead', definition: 'To work dough by pressing, folding, and stretching to develop gluten. Essential for bread-making.' },
  { term: 'Lard', definition: 'To insert strips of fat into lean meat before cooking to add moisture and flavor.' },
  { term: 'Leavening', definition: 'Agents (yeast, baking powder, baking soda) that cause dough or batter to rise.' },
  { term: 'Marinate', definition: 'To soak food in a mixture of oil, acid, and seasonings for a period of time to add flavor and tenderize.' },
  { term: 'Mince', definition: 'To cut food into very small pieces, finer than a chop.' },
  { term: 'Mirepoix', definition: 'A mixture of diced onions, carrots, and celery used as a flavor base for stocks, soups, and sauces.' },
  { term: 'Mise en place', definition: 'French for "everything in its place." Preparing and organizing ingredients before cooking.' },
  { term: 'Parboil', definition: 'To partially boil food. Often used for vegetables that will be finished by another cooking method.' },
  { term: 'Pare', definition: 'To remove the outer skin of fruit or vegetables with a knife or peeler.' },
  { term: 'Pickle', definition: 'To preserve food in vinegar, brine, or another acidic solution.' },
  { term: 'Pinch', definition: 'A small amount of an ingredient held between thumb and forefinger, roughly 1/16 teaspoon.' },
  { term: 'Poach', definition: 'To cook food gently in liquid at temperatures just below boiling. Common for eggs and fish.' },
  { term: 'Proof', definition: 'To allow dough to rise. Also, to proof yeast by dissolving it in warm water to confirm it is active.' },
  { term: 'Purée', definition: 'To blend or mash food into a smooth, uniform paste. Can be done with a blender, food processor, or mortar.' },
  { term: 'Reduce', definition: 'To boil a liquid to concentrate and thicken it by evaporating water.' },
  { term: 'Rest', definition: 'To let cooked meat sit before slicing. Allows juices to redistribute for a moister result.' },
  { term: 'Roux', definition: 'A mixture of equal parts fat and flour cooked together. Used as a thickening agent for sauces and soups.' },
  { term: 'Roast', definition: 'To cook food in an oven using dry heat, typically at higher temperatures. Often used for large cuts of meat.' },
  { term: 'Sauté', definition: 'To cook food quickly in a small amount of fat over medium-high heat, often with constant movement.' },
  { term: 'Score', definition: 'To cut shallow lines or slits into the surface of food. Helps with even cooking, absorption, or presentation.' },
  { term: 'Sear', definition: 'To brown the surface of food quickly at high heat to develop flavor and create a crust.' },
  { term: 'Shred', definition: 'To cut or tear food into long, thin strips. Often used for cheese, cabbage, or cooked meat.' },
  { term: 'Simmer', definition: 'To cook in liquid at a temperature just below boiling, with gentle bubbles.' },
  { term: 'Slice', definition: 'To cut food into flat, thin pieces. Thickness can vary.' },
  { term: 'Smoke', definition: 'To expose food to smoke from burning wood or other materials for flavor and preservation.' },
  { term: 'Steam', definition: 'To cook food in the vapor produced by boiling water, without submerging the food.' },
  { term: 'Steep', definition: 'To soak food (e.g., tea, spices) in hot liquid to extract flavor.' },
  { term: 'Stir-fry', definition: 'To cook small pieces of food quickly in a wok or skillet over high heat with constant stirring.' },
  { term: 'Stock', definition: 'A flavorful liquid made by simmering bones, vegetables, and aromatics. Base for soups and sauces.' },
  { term: 'Strain', definition: 'To pass a liquid or mixture through a sieve or strainer to remove solids.' },
  { term: 'Sweat', definition: 'To cook vegetables in fat over low heat until they release moisture and soften without browning.' },
  { term: 'Temper', definition: 'To slowly add a hot liquid to eggs or another sensitive ingredient while stirring, to raise temperature without curdling.' },
  { term: 'Thicken', definition: 'To add a binding agent (flour, cornstarch, egg) to a liquid to increase its viscosity.' },
  { term: 'Truss', definition: 'To tie poultry or meat with string to create a compact shape for even cooking.' },
  { term: 'Velouté', definition: 'A French sauce made from stock (chicken, fish, or veal) thickened with a blond roux. One of the five mother sauces.' },
  { term: 'Whip', definition: 'To beat a liquid (cream, egg whites) vigorously to incorporate air and increase volume.' },
  { term: 'Zest', definition: 'The outer colored part of citrus peel. Contains aromatic oils; used for flavor without the bitter pith.' },
  { term: 'Almond paste', definition: 'A mixture of ground almonds and sugar used in pastries and confections.' },
  { term: 'Bordelaise', definition: 'A French sauce made with red wine, shallots, and bone marrow, often served with steak.' },
  { term: 'Breadcrumb', definition: 'Crumbled or ground dried bread used for coating foods or as a topping.' },
  { term: 'Broth', definition: 'A flavorful liquid made by simmering meat, vegetables, or both. Lighter than stock.' },
  { term: 'Butterfly cut', definition: 'Splitting food horizontally and opening it flat for even cooking.' },
  { term: 'Canape', definition: 'A small appetizer consisting of a base (bread, cracker) topped with savory spread or garnish.' },
  { term: 'Carryover cooking', definition: 'The continued cooking of food after it is removed from heat, due to residual heat.' },
  { term: 'Chinois', definition: 'A cone-shaped fine-mesh strainer used for straining sauces and purées.' },
  { term: 'Coddle', definition: 'To cook gently in water just below boiling, often used for eggs.' },
  { term: 'Crimp', definition: 'To seal pastry edges by pressing or pinching, as with pie crusts.' },
  { term: 'Dashi', definition: 'Japanese stock made from kombu and bonito flakes; base for miso soup and other dishes.' },
  { term: 'Devein', definition: 'To remove the dark vein from the back of shrimp.' },
  { term: 'Dollop', definition: 'A small, irregular amount of a soft food (e.g., sour cream) placed on a dish.' },
  { term: 'Dry rub', definition: 'A mixture of spices and herbs rubbed onto meat before cooking.' },
  { term: 'Egg wash', definition: 'Beaten egg (often with milk) brushed on pastry for a golden finish.' },
  { term: 'Espagnole', definition: 'A brown sauce made from brown stock and brown roux; one of the five French mother sauces.' },
  { term: 'Fricassee', definition: 'A cooking method where meat is sautéed then braised in liquid, often with a white sauce.' },
  { term: 'Frittata', definition: 'An Italian open-faced omelet with ingredients mixed in, often finished in the oven.' },
  { term: 'Fumet', definition: 'A concentrated fish stock used as a base for sauces.' },
  { term: 'Galette', definition: 'A free-form pastry or flat cake, often with a savory or sweet filling.' },
  { term: 'Ganache', definition: 'A rich mixture of chocolate and cream used for frosting, fillings, or truffles.' },
  { term: 'Gelatinize', definition: 'To cause starch to absorb liquid and swell, as when making a roux or pudding.' },
  { term: 'Gluten', definition: 'Protein in wheat flour that develops when kneaded; gives structure to bread.' },
  { term: 'Gratin', definition: 'A dish with a browned crust, often of cheese or breadcrumbs.' },
  { term: 'Griddle', definition: 'A flat cooking surface, often used for pancakes and grilled sandwiches.' },
  { term: 'Hull', definition: 'To remove the stem and leafy cap from strawberries or similar fruit.' },
  { term: 'Jus', definition: 'French for juice; the natural juices from roasted meat, often served as a sauce.' },
  { term: 'Kosher salt', definition: 'Coarse salt with no additives; preferred by many chefs for seasoning.' },
  { term: 'Leaven', definition: 'To cause dough or batter to rise using yeast, baking powder, or baking soda.' },
  { term: 'Macerate', definition: 'To soften or flavor food by soaking in liquid, often sugar or alcohol.' },
  { term: 'Mandoline', definition: 'A slicer with adjustable blades for cutting uniform thin slices.' },
  { term: 'Mash', definition: 'To crush food (e.g., potatoes) into a smooth mixture.' },
  { term: 'Mother sauces', definition: 'The five French base sauces: béchamel, velouté, espagnole, hollandaise, and tomato.' },
  { term: 'Pâte à choux', definition: 'A cooked dough used for éclairs, cream puffs, and gougères.' },
  { term: 'Pâté', definition: 'A spreadable mixture of ground meat, liver, or vegetables, often served as an appetizer.' },
  { term: 'Plank', definition: 'To cook food (often fish) on a wooden board over heat, infusing smoky flavor.' },
  { term: 'Prick', definition: 'To pierce pastry with a fork before baking to prevent puffing.' },
  { term: 'Render', definition: 'To melt fat away from meat by cooking slowly.' },
  { term: 'Scald', definition: 'To heat milk to just below boiling, often to kill bacteria or prepare for yeast.' },
  { term: 'Shuck', definition: 'To remove the shell from shellfish or the husk from corn.' },
  { term: 'Spatchcock', definition: 'To flatten a bird by removing the backbone so it cooks evenly.' },
  { term: 'Supreme', definition: 'A citrus segment with all pith and membrane removed.' },
  { term: 'Tournée', definition: 'To cut vegetables into a football shape with seven equal sides.' },
  { term: 'Wet rub', definition: 'A paste of spices and liquid (oil, vinegar) applied to meat before cooking.' },
];
