/**
 * Comprehensive list of units for inventory and recipe ingredients.
 * Sorted alphabetically (empty string first for "no unit").
 */

export const INVENTORY_UNITS = [
  '',
  'bag',
  'bags',
  'block',
  'blocks',
  'bottle',
  'bottles',
  'box',
  'boxes',
  'bunch',
  'can',
  'cans',
  'cl',
  'clove',
  'cloves',
  'container',
  'containers',
  'cube',
  'cubes',
  'cup',
  'cups',
  'dash',
  'drop',
  'drops',
  'ear',
  'ears',
  'fl oz',
  'fluid ounce',
  'fluid ounces',
  'g',
  'gallon',
  'gallons',
  'gram',
  'grams',
  'head',
  'heads',
  'jar',
  'jars',
  'kg',
  'lb',
  'leaf',
  'leaves',
  'liter',
  'liters',
  'loaf',
  'loaves',
  'lbs',
  'ml',
  'ounce',
  'ounces',
  'oz',
  'package',
  'packages',
  'piece',
  'pieces',
  'pinch',
  'pint',
  'pints',
  'pound',
  'pounds',
  'quart',
  'quarts',
  'sheet',
  'sheets',
  'shot',
  'slice',
  'slices',
  'splash',
  'sprig',
  'sprigs',
  'stalk',
  'stalks',
  'strip',
  'strips',
  'tablespoon',
  'tablespoons',
  'tbsp',
  'teaspoon',
  'teaspoons',
  'tsp',
] as const;

/** Map equivalent units to a canonical form for merge matching. */
const UNIT_CANONICAL: Record<string, string> = {
  gallons: 'gallon',
  cups: 'cup',
  tablespoons: 'tablespoon',
  tbsp: 'tablespoon',
  teaspoons: 'teaspoon',
  tsp: 'teaspoon',
  ounces: 'oz',
  pound: 'lb',
  pounds: 'lb',
  grams: 'g',
  cloves: 'clove',
  pieces: 'piece',
  slices: 'slice',
  sprigs: 'sprig',
  stalks: 'stalk',
  bags: 'bag',
  blocks: 'block',
  bottles: 'bottle',
  boxes: 'box',
  cans: 'can',
  containers: 'container',
  cubes: 'cube',
  drops: 'drop',
  ears: 'ear',
  'fluid ounce': 'fl oz',
  'fluid ounces': 'fl oz',
  heads: 'head',
  jars: 'jar',
  leaves: 'leaf',
  liters: 'liter',
  loaves: 'loaf',
  packages: 'package',
  pints: 'pint',
  quarts: 'quart',
  sheets: 'sheet',
  strips: 'strip',
};

export function getUnitMergeKey(unit: string): string {
  const u = unit.toLowerCase().trim();
  if (!u) return '';
  return UNIT_CANONICAL[u] || u;
}
